# Generated by Django 6.0.7 on 2026-08-05 17:50

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('android_file', models.FileField(blank=True, help_text='Upload the Android APK (.apk only).', null=True, upload_to='apps/android/', validators=[store.models.validate_apk_file], verbose_name='Android APK')),
                ('windows_file', models.FileField(blank=True, help_text='Upload the Windows installer (.exe only).', null=True, upload_to='apps/windows/', validators=[store.models.validate_exe_file], verbose_name='Windows EXE')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', validators=[store.models.validate_icon_image])),
                ('android_download_count', models.PositiveIntegerField(default=0, verbose_name='Android downloads')),
                ('windows_download_count', models.PositiveIntegerField(default=0, verbose_name='Windows downloads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'ordering': ['-created_at'],
            },
        ),
    ]
