# Generated by Django 6.0.7 on 2026-08-05 18:42

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(default='support@appstore.local', max_length=254)),
                ('site_tagline', models.CharField(default='Discover & download Android and Windows apps', max_length=200)),
                ('about_text', models.TextField(blank=True, default='AppStore is a simple private app distribution portal. Admins upload Android APK and Windows EXE builds; signed-in users browse and download them.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
        migrations.AddField(
            model_name='app',
            name='android_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='app',
            name='changelog',
            field=models.TextField(blank=True, help_text="What's new in this version.", verbose_name="What's new"),
        ),
        migrations.AddField(
            model_name='app',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured apps appear at the top of the homepage.'),
        ),
        migrations.AddField(
            model_name='app',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Unpublished (draft) apps are hidden from the storefront.'),
        ),
        migrations.AddField(
            model_name='app',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Show a “Verified by admin” trust badge.'),
        ),
        migrations.AddField(
            model_name='app',
            name='requirements',
            field=models.TextField(blank=True, help_text='e.g. Android 8+ / Windows 10+', verbose_name='System requirements'),
        ),
        migrations.AddField(
            model_name='app',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='app',
            name='windows_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('upload', 'Uploaded'), ('update', 'Updated'), ('delete', 'Deleted'), ('publish', 'Published'), ('unpublish', 'Unpublished'), ('download', 'Downloaded')], max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='store.app')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/', validators=[store.models.validate_icon_image])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='store.app')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
